version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    # env_file:
    #   - .env.docker-compose

  # mongodb:
  #   image: bitnami/mongodb:latest
  #   ports:
  #     - "27017"
  #   volumes:
  #     - data:/bitnami/mongodb
# volumes:
#   data:
